#sdk: "/Users/balajidl/.rvm/gems/ruby-1.9.2-p290/gems/rhodes-3.3.3.5.26.0.beta"
sdkversion: 3.3.3
name: restful_crud_rhomobile_sample
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.restfulcrudrhomobilesample
  BundleURLScheme: restfulcrudrhomobilesample
wp:
  productid: bc8f0300-887c-012f-1d70-482a14274cb5
symbian:
  uid: 0xe38f01d6
android:
  version: 2.1
extensions:
  - json
